### ISSUE TITLE
请教一下有关noninclusive 和inclusive的问题

### ISSUE THREAD

**Issue by user-stu-l** [OpenXiangShan/HuanCun#124]
您好，我从更新的缓存代码里发现你们主要更新的是noninclusive策略的代码，并未过多关注和修改inclusive部分，这是出于什么考虑呢？noninclusive相比而言有什么具体优劣呢？谢谢

**Comment by wakafa1** [comment]
因为我们香山第二代架构南湖使用了 non-inclusive 配置的缓存。
noninclusive 策略的优劣可以参考相关学术资料。简单来说具有容量优势和traffic劣势

**Comment by user-stu-l** [comment]
谢谢您的解答，不过根据您的解答可以理解为香山第二代南湖架构inclusive的相比nonexclusive有些功能是不完善的（如cmo控制等），inclusive也未充分验证吗？

**Comment by wakafa1** [comment]
是的，inclusive没有充分验证
