### ISSUE TITLE
关于TileLink协议

### ISSUE THREAD

**Issue by changekkk** [OpenXiangShan/HuanCun#156]
请教一下，咱们目前核内和缓存按照TileLink协议，这个协议对于后续更多核的设计和高性能设计有局限性吗？ 后续是否考虑一直延续使用这个协议？

**Comment by wakafa1** [comment]
有局限性。我们以后会考虑使用 AMBA5 CHI 协议，可能最早会在昆明湖 V2 版本上落地。

**Comment by changekkk** [comment]
这里的局限性主要体现在哪些方面呢？

**Comment by wakafa1** [comment]
缺乏网络层支持、缺乏数据控制分离、缺乏复杂opcode语义等

**Comment by changekkk** [comment]
好的，谢谢

**Comment by changekkk** [comment]
你好，再问一下，这里如果使用CHI的话，相关缓存一致性和核间验证方式采用什么方案呢？目前的TlTest只能真谛TileLink协议，到时候CHI的协议检查，类似bus  rule checker的逻辑，是自己开发吗？还是借助一些商业VIP来验证？

**Comment by wakafa1** [comment]
> 你好，再问一下，这里如果使用CHI的话，相关缓存一致性和核间验证方式采用什么方案呢？目前的TlTest只能真谛TileLink协议，到时候CHI的协议检查，类似bus rule checker的逻辑，是自己开发吗？还是借助一些商业VIP来验证？

具体方案我们正在内部讨论中，欢迎提供建议
